### PR TITLE
Bugfix: zoom behavior

### LINKED ISSUE #128: Weird zoom behavior
**Describe the bug**

When we try to zoom in or zoom out, the center of the viewport is not link to mouse position. So we have a weird zoom effect.

### PR DESCRIPTION
**Pull request by Hundraw**
Close #128

### CODE REVIEW

File: src/draw/DefaultDrawer.js [hunk 1]
```diff
@@ -903,14 +903,14 @@ class DefaultDrawer {
    *
    * @param {object} element - D3 element related to the actions.
```
Comment (Zorin95670) [inline src/draw/DefaultDrawer.js:904]: Missing update documentation

**Review by Zorin95670 — CHANGES_REQUESTED** [review]

**Review by Zorin95670 — APPROVED** [review]
